package com.nestling.youtubeplayer

import android.util.Log
import java.io.IOException
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException
import org.schabi.newpipe.extractor.exceptions.ReCaptchaException
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.DeliveryMethod
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.StreamType
import org.schabi.newpipe.extractor.stream.VideoStream

/**
 * Resolves an approved video ID into short-lived, authorized playback data.
 *
 * The caller is responsible for approval: the React Native layer only passes a video ID that
 * already satisfied `ContentAccessService`, and this resolver never decides what may be watched.
 * Resolved URLs are short-lived and are never persisted.
 */
interface YouTubePlaybackResolver {
  /**
   * @param preferAdaptive false forces the muxed progressive stream, used once adaptive playback
   * has already failed for this video so a broken manifest cannot loop into a dead playback.
   */
  fun resolve(videoId: String, preferAdaptive: Boolean = true): PlaybackInfo
}

/**
 * Resolves playback through NewPipeExtractor.
 *
 * Prefers YouTube's adaptive HLS ladder, which is the only rendition set that is not throttled
 * server-side, and falls back to a muxed progressive stream, which tops out at 360p.
 */
class AuthorizedPlaybackResolver(
  private val qualitySelector: QualitySelector = DefaultQualitySelector(),
  private val quality: PlaybackQuality = PlaybackQuality.AUTO,
) : YouTubePlaybackResolver {

  override fun resolve(videoId: String, preferAdaptive: Boolean): PlaybackInfo {
    if (videoId.isBlank()) {
      throw PlaybackException(PlaybackCodes.INVALID_VIDEO_ID, "No video was requested.")
    }
    NewPipeSession.ensureInitialised()

    val info = try {
      StreamInfo.getInfo(ServiceList.YouTube, WATCH_URL_PREFIX + videoId)
    } catch (error: ContentNotAvailableException) {
      Log.w(TAG, "resolve($videoId) unavailable", error)
      // Covers private, deleted, paid, age-restricted and geo-blocked content: all terminal.
      throw PlaybackException(PlaybackCodes.VIDEO_UNAVAILABLE, UNAVAILABLE_MESSAGE)
    } catch (error: ReCaptchaException) {
      Log.w(TAG, "resolve($videoId) recaptcha", error)
      throw PlaybackException(PlaybackCodes.NETWORK_ERROR, RETRY_MESSAGE)
    } catch (error: IOException) {
      Log.w(TAG, "resolve($videoId) io", error)
      throw PlaybackException(PlaybackCodes.NETWORK_ERROR, RETRY_MESSAGE)
    } catch (error: Exception) {
      Log.w(TAG, "resolve($videoId) failed", error)
      throw PlaybackException(PlaybackCodes.PLAYBACK_FAILURE, UNAVAILABLE_MESSAGE)
    }

    if (info.streamType != StreamType.VIDEO_STREAM) {
      // Live streams and audio-only content are out of scope for this player.
      throw PlaybackException(PlaybackCodes.UNSUPPORTED_FORMAT, UNAVAILABLE_MESSAGE)
    }

    val captions = info.subtitles.orEmpty().filter { it.isUrl && !it.content.isNullOrBlank() }
      .mapNotNull { subtitle ->
        val mime = subtitle.format?.mimeType ?: return@mapNotNull null
        CaptionStream(subtitle.content, mime, subtitle.languageTag,
          subtitle.displayLanguageName + if (subtitle.isAutoGenerated) " (auto)" else "")
      }
    val durationMs = info.duration.takeIf { it > 0 }?.times(1000L)

    // Adaptive HLS first. The direct progressive URLs NewPipe exposes for 480p+ carry no
    // rate-bypass, so YouTube throttles them server-side and the buffer starves a few seconds
    // into playback. The HLS ladder lets ExoPlayer switch renditions to match the network
    // instead of stalling — the same mechanism the YouTube app uses.
    val hls = info.hlsUrl.takeIf { !it.isNullOrBlank() }
    if (hls != null && preferAdaptive) {
      return PlaybackInfo(
        videoId = videoId,
        durationMs = durationMs,
        captions = captions,
        manifestUrl = hls,
        mimeType = "application/x-mpegURL",
      )
    }

    // Only the HLS ladder reaches beyond 360p; the separate video-only and audio-only URLs are
    // throttled just as badly, so a forced fallback goes straight to the muxed stream.
    val audio = if (preferAdaptive) bestAudio(info.audioStreams) else null
    val adaptive = if (preferAdaptive) bestVideo(info.videoOnlyStreams) else null

    if (adaptive != null && audio != null) {
      return PlaybackInfo(
        videoId = videoId,
        durationMs = durationMs,
        captions = captions,
        videoUrl = adaptive.content,
        audioUrl = audio.content,
        mimeType = adaptive.format?.mimeType,
        height = heightOf(adaptive),
      )
    }

    val muxed = bestVideo(info.videoStreams)
      ?: throw PlaybackException(PlaybackCodes.UNSUPPORTED_FORMAT, UNAVAILABLE_MESSAGE)

    return PlaybackInfo(
      videoId = videoId,
      durationMs = durationMs,
      captions = captions,
      videoUrl = muxed.content,
      mimeType = muxed.format?.mimeType,
      height = heightOf(muxed),
    )
  }

  /**
   * Best stream ExoPlayer can fetch directly, capped by the module's existing quality policy.
   * Without the cap YouTube happily hands back a 2160p rendition a phone cannot use.
   */
  private fun bestVideo(streams: List<VideoStream>?): VideoStream? {
    val usable = streams.orEmpty().filter(::isDirectUrl)
    if (usable.isEmpty()) return null
    val target = qualitySelector.select(usable.mapNotNull(::heightOf), quality)
    return usable.firstOrNull { heightOf(it) == target }
      ?: usable.maxByOrNull { heightOf(it) ?: 0 }
  }

  private fun bestAudio(streams: List<AudioStream>?): AudioStream? =
    streams.orEmpty().filter(::isDirectUrl).maxByOrNull { it.averageBitrate }

  private fun isDirectUrl(stream: org.schabi.newpipe.extractor.stream.Stream): Boolean =
    stream.isUrl && stream.deliveryMethod == DeliveryMethod.PROGRESSIVE_HTTP && !stream.content.isNullOrBlank()

  /** `getResolution()` looks like "1080p60"; only the leading number is meaningful here. */
  private fun heightOf(stream: VideoStream): Int? =
    stream.resolution?.takeWhile { it.isDigit() }?.toIntOrNull()

  private companion object {
    const val TAG = "NestlingResolver"
    const val WATCH_URL_PREFIX = "https://www.youtube.com/watch?v="
    const val UNAVAILABLE_MESSAGE = "This video can't be played right now."
    const val RETRY_MESSAGE = "Couldn't reach the video. Trying again may help."

  }
}

class PlaybackException(val code: String, override val message: String) : Exception(message)
