import { StyleSheet } from 'react-native';
import { colors } from '../theme';
import { yt } from '../youtube/theme';

/** Parent content styles. Tokens come from `../theme`; see youtube/theme.ts for the palette. */
const styles = StyleSheet.create({
  filterLabel: { color: colors.muted, fontSize: 11, fontWeight: '900', letterSpacing: 1, marginBottom: 8, marginTop: 20 },
  chip: { backgroundColor: colors.card, borderRadius: 12, justifyContent: 'center', minHeight: 42, paddingHorizontal: 11 },
  chipActive: { backgroundColor: colors.lavender },
  chipText: { color: colors.muted, fontSize: 12, fontWeight: '800' },
  chipTextActive: { color: colors.ink },
  recentRow: { flexDirection: 'row', gap: 10 },
  recentCard: { borderRadius: 15, flex: 1, minHeight: 76, padding: 11 },
  recentTitle: { color: colors.ink, fontSize: 13, fontWeight: '800' },
  recentMeta: { color: colors.muted, fontSize: 11, marginTop: 6 },
  listLabel: { color: colors.muted, fontSize: 11, fontWeight: '900', letterSpacing: 1.1, marginBottom: 9, marginTop: 22 },
  row: { alignItems: 'center', backgroundColor: colors.card, borderRadius: 15, flexDirection: 'row', flexWrap: 'wrap', marginBottom: 8, minHeight: 74, padding: 9 },
  thumb: { borderRadius: 11, height: 52, width: 52 },
  thumbFallback: { alignItems: 'center', backgroundColor: colors.lavender, borderRadius: 11, height: 52, justifyContent: 'center', width: 52 },
  rowInfo: { flex: 1, paddingHorizontal: 11 },
  rowTitle: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  rowMeta: { color: colors.muted, fontSize: 12, marginTop: 4 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 7 },
  approvalTag: { alignItems: 'center', backgroundColor: colors.mint, borderRadius: 9, flexDirection: 'row', gap: 4, paddingHorizontal: 7, paddingVertical: 4 },
  approvalTagText: { color: colors.mintDark, fontSize: 10, fontWeight: '800' },
  expiryTag: { backgroundColor: colors.peach, borderRadius: 9, paddingHorizontal: 7, paddingVertical: 4 },
  expiryTagText: { color: colors.coral, fontSize: 10, fontWeight: '800' },
  videoCountTag: { alignItems: 'center', backgroundColor: colors.lavender, borderRadius: 9, flexDirection: 'row', gap: 4, paddingHorizontal: 7, paddingVertical: 4 },
  videoCountText: { color: colors.ink, fontSize: 10, fontWeight: '800' },
  pageHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 10, justifyContent: 'space-between', paddingBottom: 14, paddingTop: 4 },
  pageHeading: { flex: 1 },
  pageActions: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  addPill: { alignItems: 'center', backgroundColor: '#B5A6F5', borderRadius: 18, flexDirection: 'row', gap: 5, minHeight: 36, paddingHorizontal: 14 },
  addPillText: { color: '#1A1A1A', fontSize: 13, fontWeight: '700' },
  pageTitle: { color: yt.text, fontSize: 24, fontWeight: '700' },
  pageSubtitle: { color: yt.textDim, fontSize: 13, lineHeight: 18, marginTop: 3 },

  banner: { backgroundColor: '#9A8AE6', borderRadius: 20, flexDirection: 'row', marginTop: 4, overflow: 'hidden', padding: 16 },
  bannerText: { flex: 1, paddingRight: 8 },
  bannerTitle: { color: '#1A1A1A', fontSize: 20, fontWeight: '800', lineHeight: 24 },
  bannerBody: { color: '#2B2540', fontSize: 13, lineHeight: 18, marginTop: 6 },
  bannerButton: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: '#FFFFFF', borderRadius: 14, flexDirection: 'row', gap: 7, marginTop: 12, minHeight: 38, paddingHorizontal: 14 },
  bannerButtonText: { color: '#1A1A1A', fontSize: 13, fontWeight: '700' },
  bannerArt: { alignItems: 'center', alignSelf: 'center', backgroundColor: 'rgba(255,255,255,0.45)', borderRadius: 32, height: 84, justifyContent: 'center', width: 84 },

  sectionHeading: { color: yt.text, fontSize: 17, fontWeight: '700' },
  recentChannels: { gap: 12, paddingTop: 12 },
  recentChannelCard: { width: 150 },
  recentChannelPicture: { alignItems: 'center', aspectRatio: 16 / 9, backgroundColor: yt.surfaceAlt, borderRadius: 14, justifyContent: 'center', overflow: 'hidden', width: '100%' },
  recentChannelImage: { height: '100%', width: '100%' },
  recentChannelBadge: { backgroundColor: yt.badge, borderRadius: 6, bottom: 6, paddingHorizontal: 6, paddingVertical: 2, position: 'absolute', right: 6 },
  recentChannelBadgeText: { color: yt.onAccent, fontSize: 10.5, fontWeight: '700' },
  recentChannelName: { color: yt.text, fontSize: 13, fontWeight: '700', marginTop: 8 },
  recentChannelMeta: { color: yt.textDim, fontSize: 11.5, marginTop: 2 },

  listHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12, marginTop: 24 },
  sortPill: { alignItems: 'center', backgroundColor: yt.surfaceAlt, borderRadius: 16, flexDirection: 'row', gap: 6, minHeight: 32, paddingHorizontal: 12 },
  sortPillText: { color: yt.text, fontSize: 12.5, fontWeight: '600' },

  channelCard: { backgroundColor: yt.surface, borderRadius: 18, marginBottom: 10, padding: 12 },
  channelTop: { alignItems: 'flex-start', flexDirection: 'row', gap: 12 },
  channelThumb: { borderRadius: 16, height: 72, width: 72 },
  channelThumbFallback: { alignItems: 'center', backgroundColor: yt.surfaceAlt, borderRadius: 16, height: 72, justifyContent: 'center', width: 72 },
  channelBottom: { alignItems: 'center', flexDirection: 'row', gap: 8, justifyContent: 'space-between', marginTop: 10 },
  channelActions: { flexDirection: 'row', gap: 8 },
  rowAction: { alignItems: 'center', backgroundColor: yt.surfaceAlt, borderRadius: 12, height: 38, justifyContent: 'center', width: 38 },
  rowActionDanger: { alignItems: 'center', backgroundColor: '#3E1F22', borderRadius: 12, height: 38, justifyContent: 'center', width: 38 },
  backRow: { alignItems: 'center', flexDirection: 'row', gap: 10, paddingBottom: 6, paddingVertical: 8 },
  backText: { color: colors.ink, fontSize: 15, fontWeight: '800' },
  channelHero: { alignItems: 'center', gap: 6, paddingBottom: 18, paddingTop: 4 },
  heroThumb: { borderRadius: 32, height: 64, marginBottom: 4, width: 64 },
  heroName: { color: colors.ink, fontSize: 19, fontWeight: '800', textAlign: 'center' },
  heroMeta: { color: colors.muted, fontSize: 13 },
  iconButton: { alignItems: 'center', height: 48, justifyContent: 'center', width: 42 },
  categoryEditor: { borderTopColor: colors.line, borderTopWidth: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10, paddingTop: 12, width: '100%' },
  empty: { backgroundColor: colors.card, borderRadius: 15, marginBottom: 8, padding: 16 },
});

export default styles;
