import { StyleSheet } from 'react-native';
import { colors } from '../theme';
import { yt } from '../youtube/theme';

/** Parent content styles. Tokens come from `../theme`; see youtube/theme.ts for the palette. */
const styles = StyleSheet.create({
  intro: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 26 },
  title: { color: colors.ink, fontSize: 20, fontWeight: '800' },
  subtitle: { color: colors.muted, fontSize: 13, marginTop: 4 },
  privacyBadge: { alignItems: 'center', backgroundColor: colors.mint, borderRadius: 12, flexDirection: 'row', gap: 5, paddingHorizontal: 10, paddingVertical: 8 },
  privacyText: { color: colors.mintDark, fontSize: 11, fontWeight: '800' },
  tabRow: { flexDirection: 'row', gap: 8, marginTop: 18 },
  tab: { alignItems: 'center', backgroundColor: colors.card, borderRadius: 13, flexDirection: 'row', gap: 7, minHeight: 46, paddingHorizontal: 13 },
  tabActive: { backgroundColor: colors.lavender },
  tabText: { color: colors.muted, fontSize: 13, fontWeight: '800' },
  tabTextActive: { color: colors.ink },
  input: { backgroundColor: colors.canvas, borderRadius: 13, color: colors.ink, fontSize: 15, height: 50, marginTop: 14, paddingHorizontal: 13 },
  filterLabel: { color: colors.muted, fontSize: 11, fontWeight: '900', letterSpacing: 1, marginBottom: 8, marginTop: 20 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { backgroundColor: colors.card, borderRadius: 12, justifyContent: 'center', minHeight: 42, paddingHorizontal: 11 },
  chipActive: { backgroundColor: colors.lavender },
  chipText: { color: colors.muted, fontSize: 12, fontWeight: '800' },
  chipTextActive: { color: colors.ink },
  recentRow: { flexDirection: 'row', gap: 10 },
  recentCard: { borderRadius: 15, flex: 1, minHeight: 76, padding: 11 },
  recentTitle: { color: colors.ink, fontSize: 13, fontWeight: '800' },
  recentMeta: { color: colors.muted, fontSize: 11, marginTop: 6 },
  listLabel: { color: colors.muted, fontSize: 11, fontWeight: '900', letterSpacing: 1.1, marginBottom: 9, marginTop: 22 },
  row: { alignItems: 'center', backgroundColor: colors.card, borderRadius: 15, flexDirection: 'row', flexWrap: 'wrap', marginBottom: 8, minHeight: 74, padding: 9 },
  thumb: { borderRadius: 11, height: 52, width: 52 },
  thumbFallback: { alignItems: 'center', backgroundColor: colors.lavender, borderRadius: 11, height: 52, justifyContent: 'center', width: 52 },
  rowInfo: { flex: 1, paddingHorizontal: 11 },
  rowTitle: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  rowMeta: { color: colors.muted, fontSize: 12, marginTop: 4 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 7 },
  approvalTag: { alignItems: 'center', backgroundColor: colors.mint, borderRadius: 9, flexDirection: 'row', gap: 4, paddingHorizontal: 7, paddingVertical: 4 },
  approvalTagText: { color: colors.mintDark, fontSize: 10, fontWeight: '800' },
  expiryTag: { backgroundColor: colors.peach, borderRadius: 9, paddingHorizontal: 7, paddingVertical: 4 },
  expiryTagText: { color: '#8A5340', fontSize: 10, fontWeight: '800' },
  videoCountTag: { alignItems: 'center', backgroundColor: colors.lavender, borderRadius: 9, flexDirection: 'row', gap: 4, paddingHorizontal: 7, paddingVertical: 4 },
  videoCountText: { color: colors.ink, fontSize: 10, fontWeight: '800' },
  pageHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingBottom: 14, paddingTop: 4 },
  pageTitle: { color: yt.text, fontSize: 20, fontWeight: '700' },
  backRow: { alignItems: 'center', flexDirection: 'row', gap: 10, paddingBottom: 6, paddingVertical: 8 },
  backText: { color: colors.ink, fontSize: 15, fontWeight: '800' },
  channelHero: { alignItems: 'center', gap: 6, paddingBottom: 18, paddingTop: 4 },
  heroThumb: { borderRadius: 32, height: 64, marginBottom: 4, width: 64 },
  heroName: { color: colors.ink, fontSize: 19, fontWeight: '800', textAlign: 'center' },
  heroMeta: { color: colors.muted, fontSize: 13 },
  channelVideos: { borderTopColor: colors.line, borderTopWidth: 1, marginTop: 12, paddingTop: 12, width: '100%' },
  iconButton: { alignItems: 'center', height: 48, justifyContent: 'center', width: 42 },
  categoryEditor: { borderTopColor: colors.line, borderTopWidth: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10, paddingTop: 12, width: '100%' },
  empty: { backgroundColor: colors.card, borderRadius: 15, marginBottom: 8, padding: 16 },
  searchCard: { backgroundColor: colors.card, borderRadius: 20, marginTop: 26, padding: 15 },
  searchHeader: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  searchIcon: { alignItems: 'center', backgroundColor: colors.lavender, borderRadius: 18, height: 38, justifyContent: 'center', width: 38 },
  searchHeaderText: { flex: 1 },
  searchTitle: { color: colors.ink, fontSize: 16, fontWeight: '800' },
  searchBody: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 4 },
  lookup: { alignItems: 'center', backgroundColor: colors.purple, borderRadius: 13, flexDirection: 'row', gap: 8, height: 48, justifyContent: 'center', marginTop: 12 },
  lookupText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  error: { color: colors.danger, fontSize: 12, marginTop: 10 },
  notice: { color: colors.mintDark, fontSize: 12, fontWeight: '700', marginTop: 10 },
  resultRow: { alignItems: 'center', backgroundColor: colors.canvas, borderRadius: 14, flexDirection: 'row', marginTop: 10, minHeight: 68, padding: 9 },
  resultTitleInput: { color: colors.ink, fontSize: 14, fontWeight: '800', padding: 0 },
  manualSlot: { marginTop: 18 },
  resultAction: { alignItems: 'center', backgroundColor: colors.lavender, borderRadius: 11, height: 44, justifyContent: 'center', marginRight: 6, paddingHorizontal: 12 },
  resultActionText: { color: colors.ink, fontSize: 13, fontWeight: '800' },
  resultApprove: { alignItems: 'center', backgroundColor: colors.mintDark, borderRadius: 11, height: 44, justifyContent: 'center', paddingHorizontal: 12 },
  resultApproveText: { color: '#fff', fontSize: 13, fontWeight: '800' },
});

export default styles;
